---
- name: Installation et configuration du serveur web
  hosts: web
  become: yes
  tasks:
    - name: Mise à jour du cache apt
      apt: update_cache=yes

    - name: Installation du paquet apache2
      apt: name=apache2 state=present

    - name: Copie du répertoire local site_web dans /var/www/html/
      copy:
        src: files/site_web/
        dest: /var/www/html/
        owner: www-data
        mode: '0600'

    - name: Redémarrage du service Apache
      service:
        name: apache2
        enabled: yes
        state: restarted

