- name: Acte 1 - essai web
  # On va agir sur l'hôte web dans cet acte
  hosts: web
  # Passe l'étape permettant de récupérer des informations sur
  #   l'hôte pour gagner du temps
  gather_facts: false

  # Liste des tâches associées à notre Acte
  tasks:
     - name: Run the equivalent of "apt-get update" as a separate step
       ansible.builtin.apt:
         update_cache: yes
     - name: Install apache httpd  (state=present is optional)
       ansible.builtin.apt:
             name: apache2
             state: present 
 
